data:
  input_size: 1024
  json_train_path: sampled_annotations.json
  main_dataset_folder: main_dataset
  min_category_count: 50
  num_classes: '7'
  original_folder: images/train/
  random_state: 42
  sample_size: 500
  test_size: 0.1
  val_size: 0.2
  yolo_format_folder: yolo_format
model:
  architecture: yolov9-c
  pretrained_weights: coco
train:
  batch_size: 8
  device: cuda
  epochs: 100
  learning_rate: 0.001
  num_workers: 4
  patience: 5
